<a href="https://colab.research.google.com/github/Gungun518/AI-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.\n")

Hello, World!
Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [ ]:
#4.1 Exercise on Functions
# Task 1
# Unit Converter Program

def convert_units(choice, value):
    """
    Perform unit conversion based on user's choice.

    Parameters:
        choice (int): Conversion option selected by user
        value (float): Value that needs to be converted

    Returns:
        float or None: Converted value if valid choice,
        otherwise None
    """

    # Length
    if choice == 1:          # meter → feet
        return value * 3.28084
    elif choice == 2:        # feet → meter
        return value / 3.28084

    # Weight
    elif choice == 3:        # kg → pounds
        return value * 2.20462
    elif choice == 4:        # pounds → kg
        return value / 2.20462

    # Volume
    elif choice == 5:        # liter → gallon
        return value * 0.264172
    elif choice == 6:        # gallon → liter
        return value / 0.264172

    else:
        return None


# -------- main program --------
print("Simple Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    user_choice = int(input("Enter your choice (1-6): "))
    user_value = float(input("Enter the value: "))

    answer = convert_units(user_choice, user_value)

    if answer is None:
        print("Invalid conversion type selected.")
    else:
        print("Converted value =", round(answer, 4))

except ValueError:
    print("Invalid input! Please enter numeric values only.")

Simple Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 1
Enter the value: 4
Converted value = 13.1234


In [ ]:
# Task 2


4.2 Exercise on List Manipulation:


In [ ]:

# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Return every other element starting from the first element.

    Parameters:
        lst (list): Input list.

    Returns:
        list: List containing every alternate element.
    """
    return lst[::2]


# Example
print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


4.2 Exercise on List Manipulation:

In [ ]:
#2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Return a sublist from start to end index (inclusive).

    Parameters:
        lst (list): Input list.
        start (int): Starting index.
        end (int): Ending index (inclusive).

    Returns:
        list: Extracted sublist.
    """
    return lst[start:end + 1]


# Example
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


In [ ]:
# Reverse a List using SLicing
def reverse_list(lst):
    """
    Return the reversed list using slicing.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Reversed list.
    """
    return lst[::-1]


# Example
print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


In [ ]:
# Remove the first and last elements
def remove_first_last(lst):
    """
    Remove the first and last elements of the list.

    Parameters:
        lst (list): Input list.

    Returns:
        list: List without first and last elements.
    """
    return lst[1:-1]


# Example
print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


In [ ]:
# Get the first n elements
def get_first_n(lst, n):
    """
    Return the first n elements of the list.

    Parameters:
        lst (list): Input list.
        n (int): Number of elements.

    Returns:
        list: First n elements.
    """
    return lst[:n]


# Example
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


In [ ]:
# Extract Last n elements
def get_last_n(lst, n):
    """
    Return the last n elements of the list.

    Parameters:
        lst (list): Input list.
        n (int): Number of elements.

    Returns:
        list: Last n elements.
    """
    return lst[-n:]


# Example
print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


In [ ]:
# Extract Elements in Reverse Skip Order
def reverse_skip(lst):
    """
    Return every second element in reverse order starting
    from the second-to-last element.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Extracted elements.
    """
    return lst[-2::-2]


# Example
print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


4.3 Exercise on Nested List:

In [ ]:
def flatten(lst):
    """
    Flatten a nested list by one level.

    Parameters:
        lst (list): Nested list.

    Returns:
        list: Flattened list.
    """
    result = []
    for item in lst:
        result.extend(item)
    return result


# Example
print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    """
    Access an element from a nested list using given indices.

    Parameters:
        lst (list): Nested list.
        indices (list): List of indices.

    Returns:
        element: The accessed element.
    """
    element = lst
    for idx in indices:
        element = element[idx]
    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))

6


In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list.

    Parameters:
        lst (list): Nested list.

    Returns:
        int/float: Sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# Example
print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


In [ ]:
def remove_element(lst, elem):
    """
    Remove all occurrences of elem from a nested list.

    Parameters:
        lst (list): Nested list.
        elem: Element to remove.

    Returns:
        list: Modified list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            cleaned = remove_element(item, elem)
            if cleaned:
                result.append(cleaned)
        elif item != elem:
            result.append(item)
    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
print(remove_element(lst, 2))

[[1], [3], [4, 5]]


In [ ]:
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
        lst (list): Nested list.

    Returns:
        int/float: Maximum element.
    """
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val


# Example
print(find_max([[1, 2], [3, [4, 5]], 6]))



6


In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times elem appears in a nested list.

    Parameters:
        lst (list): Nested list.
        elem: Element to count.

    Returns:
        int: Number of occurrences.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
print(count_occurrences(lst, 2))  # Output: 3

3


In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
        lst (list): Deeply nested list.

    Returns:
        list: Fully flattened list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


# Example
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
# Output: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Parameters:
        lst (list): Nested list.

    Returns:
        float: Average value.
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat) if flat else 0


# Example
print(average_nested([[1, 2], [3, 4], [5, 6]]))  # Output: 3.5

3.5


# 10 To - Do - NumPy

In [ ]:
#Problem 1: Array Creation
import numpy as np

# 1. Empty array 2x2
arr_empty = np.empty((2, 2))
print("Empty array:\n", arr_empty)

# 2. All ones array 4x2
arr_ones = np.ones((4, 2))
print("\nAll ones:\n", arr_ones)

# 3. Array filled with specific value
arr_full = np.full((3, 3), 7)
print("\nFull array:\n", arr_full)

# 4. Zeros like given array
arr_zeros_like = np.zeros_like(arr_full)
print("\nZeros like:\n", arr_zeros_like)

# 5. Ones like given array
arr_ones_like = np.ones_like(arr_full)
print("\nOnes like:\n", arr_ones_like)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\nFrom list:", arr_from_list)

Empty array:
 [[1.63515789e-315 0.00000000e+000]
 [6.59737730e-310 6.63971683e-310]]

All ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

From list: [1 2 3 4]


In [ ]:
# Problem 2: Array Manipulation
# 1. Array from 10 to 49
arr_range = np.arange(10, 50)
print("\nRange 10–49:\n", arr_range)

# 2. 3x3 matrix from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix:\n", matrix_3x3)

# 3. Identity matrix
identity = np.eye(3)
print("\nIdentity:\n", identity)

# 4. Random array size 30 and mean
rand_30 = np.random.random(30)
print("\nMean:", rand_30.mean())

# 5. 10x10 random array min & max
rand_10x10 = np.random.random((10, 10))
print("\nMin:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array size 10, replace 5th element
zero_10 = np.zeros(10)
zero_10[4] = 1
print("\nModified zero array:", zero_10)

# 7. Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
print("\nReversed:", arr[::-1])

# 8. 2D array with border 1 and inside 0
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\nBorder array:\n", border)

# 9. Checkerboard 8x8
checker = np.zeros((8, 8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\nCheckerboard:\n", checker)


Range 10–49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean: 0.5598801451202083

Min: 0.0012859280334797107 Max: 0.9881810888278685

Modified zero array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Problem 3: Array Operation
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Addition
print("\nAdd:\n", x + y)

# 2. Subtraction
print("\nSubtract:\n", x - y)

# 3. Multiply by integer
print("\nMultiply by 3:\n", x * 3)

# 4. Square each element
print("\nSquare:\n", x ** 2)

# 5. Dot products
print("\nDot v·w:", np.dot(v, w))
print("Dot x·v:\n", np.dot(x, v))
print("Dot x·y:\n", np.dot(x, y))

# 6. Concatenation
print("\nConcat x & y (rows):\n", np.vstack((x, y)))
print("\nConcat v & w (columns):\n", np.vstack((v, w)).T)

# 7. Concatenate x and v (will error)
try:
    np.concatenate((x, v))
except Exception as e:
    print("\nError:", e)
    print("Reason: x is 2D and v is 1D — dimensions do not match.")


Add:
 [[ 6  8]
 [10 13]]

Subtract:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot v·w: 219
Dot x·v:
 [29 77]
Dot x·y:
 [[19 22]
 [50 58]]

Concat x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concat v & w (columns):
 [[ 9 11]
 [10 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D and v is 1D — dimensions do not match.


In [ ]:
# Problem 4: Matrix Operations
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)
print("\nA * A⁻¹:\n", np.dot(A, A_inv))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
left = (AB).T
right = np.dot(B.T, A.T)
print("\n(AB)^T:\n", left)
print("\nB^T A^T:\n", right)


A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


In [ ]:
# Matrix form AX = B
A_eq = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B_eq = np.array([-1, -3, 9])

# Solve using inverse
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)

print("\nSolution [x, y, z]:\n", X)


Solution [x, y, z]:
 [ 2.  1. -2.]
